#!/bin/bash

sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
if [[ $(xrandr -q | grep "HDMI-1 connected") ]]; then
  xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal --output eDP-1 --mode 1920x1080 --rotate normal --right-of HDMI-1
fi 

bspc monitor eDP-1 -d 6 7 8 9 10
bspc monitor HDMI-1 -d 1 2 3 4 5
  

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Zathura state=tiled
bspc rule -a Tk state=floating

feh --bg-fill --randomize ~/Pictures/Wallpapers/*
$HOME/.config/polybar/grayblocks/launch.sh
